language: node_js
node_js:
 - node
script:
 - npm test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 1d31ebec-b5f6-4b2f-b4aa-5e312825ac84
  app: radiant-shelf-91425